### ISSUE TITLE
ObjectID.next not working with collections

### ISSUE THREAD

**Issue by gjost** [densho/ddr-idservice#6]
IDservice is not returning IDs for new collections

```
idservice runserver
--------------------
[10/Aug/2017 13:50:20] "GET /api/0.1/rest-auth/user/ HTTP/1.0" 200 105
[10/Aug/2017 13:50:22] "POST /api/0.1/objectids/ddr-testing/next/collection/ HTTP/1.0" 500 27

idservice.log
--------------------
2017-08-10 13:50:22,016 DEBUG    [views.next_object]  next_object(<rest_framework.request.Request object at 0x7ff67957a950>, ddr-testing, collection)
2017-08-10 13:50:22,040 ERROR    [exception.handle_uncaught_exception]  Internal Server Error: /api/0.1/objectids/ddr-testing/next/collection/
Traceback (most recent call last):
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "/usr/local/src/ddr-idservice/idservice/registrar/views.py", line 90, in next_object
    next_object = ObjectID.next(oi, model)
  File "/usr/local/src/ddr-idservice/idservice/registrar/models.py", line 195, in next
    last = identifier.max_id(model, identifiers)
  File "/usr/local/src/ddr-idservice/venv/idservice/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/identifier.py", line 762, in max_id
    raise Exception('New id not in given list: %s' % oi)
Exception: New id not in given list: <DDR.identifier.Identifier collection:ddr-densho-40030>
```

**Comment by gjost** [comment]
Removed requirement of new ID to be in list of existing IDs (duh) in `ddr-cmdln` 8b218a.

**Comment by gjost** [comment]
Asked for new `ddr-testing` collection ID, got this:
```
2017-08-10 15:15:36,783 DEBUG    [views.next_object]  next_object(<rest_framework.request.Request object at 0x7f01bd2db590>, ddr-testing, collection)
2017-08-10 15:15:36,844 DEBUG    [views.next_object]  400 Invalid serializer ObjectIDSerializer(context={'request': <rest_framework.request.Request object>}, data={'url': u'/api/0.1/objectids/ddr-densho-40031/', 'model': 'collection', 'group': <Group: densho>, 'id': 'ddr-densho-40031'}):
    url = HyperlinkedIdentityField(view_name='objectid-detail')
    id = CharField(label='Object ID', max_length=255, validators=[<UniqueValidator(queryset=ObjectID.objects.all())>])
    model = CharField(max_length=255)
    group = ReadOnlyField(source='group.name')
```
Should be `ddr-testing` not `ddr-densho`.

**Comment by gjost** [comment]
Turns out the problem was `ddr-densho-40013` which was created with the wrong Django Group (`testing`).  This caused various mixups in the `registrar.views.next_object` function.
